//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::Framework;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "AI_Models")]
pub struct Model {
    #[sea_orm(column_name = "Id", primary_key)]
    pub id: u32,
    #[sea_orm(column_name = "Name", unique)]
    pub name: String,
    #[sea_orm(column_name = "Description", column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_name = "ModelPath")]
    pub model_path: Option<String>,
    #[sea_orm(column_name = "Framework")]
    pub framework: Framework,
    #[sea_orm(column_name = "Version")]
    pub version: Option<String>,
    #[sea_orm(column_name = "DatasetId")]
    pub dataset_id: Option<u32>,
    #[sea_orm(column_name = "Enabled")]
    pub enabled: u8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ai_datasets::Entity",
        from = "Column::DatasetId",
        to = "super::ai_datasets::Column::Id",
        on_update = "Restrict",
        on_delete = "SetNull"
    )]
    AiDatasets,
}

impl Related<super::ai_datasets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiDatasets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
