//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "AI_Object_Classes")]
pub struct Model {
    #[sea_orm(column_name = "Id", primary_key)]
    pub id: u32,
    #[sea_orm(column_name = "DatasetId")]
    pub dataset_id: u32,
    #[sea_orm(column_name = "ClassName")]
    pub class_name: String,
    #[sea_orm(column_name = "ClassIndex")]
    pub class_index: u32,
    #[sea_orm(column_name = "Description", column_type = "Text", nullable)]
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ai_datasets::Entity",
        from = "Column::DatasetId",
        to = "super::ai_datasets::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    AiDatasets,
}

impl Related<super::ai_datasets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiDatasets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
