//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Config")]
pub struct Model {
    #[sea_orm(column_name = "Id")]
    pub id: u16,
    #[sea_orm(column_name = "Name", primary_key, auto_increment = false)]
    pub name: String,
    #[sea_orm(column_name = "Value", column_type = "Text")]
    pub value: String,
    #[sea_orm(column_name = "Type", column_type = "custom(\"TINYTEXT\")")]
    pub r#type: String,
    #[sea_orm(column_name = "DefaultValue", column_type = "Text", nullable)]
    pub default_value: Option<String>,
    #[sea_orm(column_name = "Hint", column_type = "custom(\"TINYTEXT\")", nullable)]
    pub hint: Option<String>,
    #[sea_orm(
        column_name = "Pattern",
        column_type = "custom(\"TINYTEXT\")",
        nullable
    )]
    pub pattern: Option<String>,
    #[sea_orm(column_name = "Format", column_type = "custom(\"TINYTEXT\")", nullable)]
    pub format: Option<String>,
    #[sea_orm(column_name = "Prompt", column_type = "custom(\"TINYTEXT\")", nullable)]
    pub prompt: Option<String>,
    #[sea_orm(column_name = "Help", column_type = "Text", nullable)]
    pub help: Option<String>,
    #[sea_orm(column_name = "Category")]
    pub category: String,
    #[sea_orm(column_name = "Readonly")]
    pub readonly: u8,
    #[sea_orm(column_name = "Private")]
    pub private: i8,
    #[sea_orm(column_name = "System")]
    pub system: i8,
    #[sea_orm(column_name = "Requires", column_type = "Text", nullable)]
    pub requires: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
