//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ControlPresets")]
pub struct Model {
    #[sea_orm(column_name = "MonitorId", primary_key, auto_increment = false)]
    pub monitor_id: u32,
    #[sea_orm(column_name = "Preset", primary_key, auto_increment = false)]
    pub preset: u32,
    #[sea_orm(column_name = "Label")]
    pub label: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
