//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Events_Tags")]
pub struct Model {
    #[sea_orm(column_name = "TagId", primary_key, auto_increment = false)]
    pub tag_id: u64,
    #[sea_orm(column_name = "EventId", primary_key, auto_increment = false)]
    pub event_id: u64,
    #[sea_orm(column_name = "AssignedDate")]
    pub assigned_date: Option<DateTimeUtc>,
    #[sea_orm(column_name = "AssignedBy")]
    pub assigned_by: Option<u32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::events::Entity",
        from = "Column::EventId",
        to = "super::events::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Events,
    #[sea_orm(
        belongs_to = "super::tags::Entity",
        from = "Column::TagId",
        to = "super::tags::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Tags,
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl Related<super::tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tags.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
