//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Events_Week")]
pub struct Model {
    #[sea_orm(column_name = "EventId", primary_key, auto_increment = false)]
    pub event_id: u32,
    #[sea_orm(column_name = "MonitorId")]
    pub monitor_id: u32,
    #[sea_orm(column_name = "StartDateTime")]
    pub start_date_time: Option<DateTime>,
    #[sea_orm(column_name = "DiskSpace")]
    pub disk_space: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
