//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Event_Data")]
pub struct Model {
    #[sea_orm(column_name = "Id", primary_key)]
    pub id: u64,
    #[sea_orm(column_name = "EventId")]
    pub event_id: Option<u64>,
    #[sea_orm(column_name = "MonitorId")]
    pub monitor_id: Option<u32>,
    #[sea_orm(column_name = "FrameId")]
    pub frame_id: Option<u32>,
    #[sea_orm(column_name = "Timestamp")]
    pub timestamp: Option<DateTimeUtc>,
    #[sea_orm(column_name = "Data", column_type = "Text", nullable)]
    pub data: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
