//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use super::sea_orm_active_enums::FrameType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Frames")]
pub struct Model {
    #[sea_orm(column_name = "Id", primary_key)]
    pub id: u64,
    #[sea_orm(column_name = "EventId")]
    pub event_id: u64,
    #[sea_orm(column_name = "FrameId")]
    pub frame_id: u32,
    #[sea_orm(column_name = "Type")]
    pub r#type: FrameType,
    #[sea_orm(column_name = "TimeStamp")]
    pub time_stamp: DateTimeUtc,
    #[sea_orm(column_name = "Delta", column_type = "Decimal(Some((8, 2)))")]
    pub delta: Decimal,
    #[sea_orm(column_name = "Score")]
    pub score: u16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
