//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Logs")]
pub struct Model {
    #[sea_orm(column_name = "Id", primary_key)]
    pub id: u32,
    #[sea_orm(column_name = "TimeKey", column_type = "Decimal(Some((16, 6)))")]
    pub time_key: Decimal,
    #[sea_orm(column_name = "Component")]
    pub component: String,
    #[sea_orm(column_name = "ServerId")]
    pub server_id: Option<u32>,
    #[sea_orm(column_name = "Pid")]
    pub pid: Option<i32>,
    #[sea_orm(column_name = "Level")]
    pub level: i8,
    #[sea_orm(column_name = "Code")]
    pub code: String,
    #[sea_orm(column_name = "Message", column_type = "Text")]
    pub message: String,
    #[sea_orm(column_name = "File")]
    pub file: Option<String>,
    #[sea_orm(column_name = "Line")]
    pub line: Option<u16>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
