//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Models")]
pub struct Model {
    #[sea_orm(column_name = "Id", primary_key)]
    pub id: u32,
    #[sea_orm(column_name = "Name")]
    pub name: String,
    #[sea_orm(column_name = "ManufacturerId")]
    pub manufacturer_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::monitor_presets::Entity")]
    MonitorPresets,
    #[sea_orm(has_many = "super::monitors::Entity")]
    Monitors,
}

impl Related<super::monitor_presets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MonitorPresets.def()
    }
}

impl Related<super::monitors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Monitors.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
