//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "MontageLayouts")]
pub struct Model {
    #[sea_orm(column_name = "Id", primary_key)]
    pub id: u32,
    #[sea_orm(column_name = "Name", column_type = "Text")]
    pub name: String,
    #[sea_orm(column_name = "UserId")]
    pub user_id: u32,
    #[sea_orm(
        column_name = "Positions",
        column_type = "custom(\"LONGTEXT\")",
        nullable
    )]
    pub positions: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
