//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Reports")]
pub struct Model {
    #[sea_orm(column_name = "Id", primary_key)]
    pub id: u32,
    #[sea_orm(column_name = "Name")]
    pub name: Option<String>,
    #[sea_orm(column_name = "FilterId")]
    pub filter_id: Option<u32>,
    #[sea_orm(column_name = "StartDateTime")]
    pub start_date_time: Option<DateTime>,
    #[sea_orm(column_name = "EndDateTime")]
    pub end_date_time: Option<DateTime>,
    #[sea_orm(column_name = "Interval")]
    pub interval: Option<u32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
