//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;
use utoipa::ToSchema;

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    serde::Serialize,
    serde::Deserialize,
    ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "Analysing")]
pub enum Analysing {
    #[sea_orm(string_value = "None")]
    None,
    #[sea_orm(string_value = "Always")]
    Always,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    serde::Serialize,
    serde::Deserialize,
    ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "AnalysisImage")]
pub enum AnalysisImage {
    #[sea_orm(string_value = "FullColour")]
    FullColour,
    #[sea_orm(string_value = "YChannel")]
    YChannel,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    serde::Serialize,
    serde::Deserialize,
    ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "AnalysisSource")]
pub enum AnalysisSource {
    #[sea_orm(string_value = "Primary")]
    Primary,
    #[sea_orm(string_value = "Secondary")]
    Secondary,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    serde::Serialize,
    serde::Deserialize,
    ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "Capturing")]
pub enum Capturing {
    #[sea_orm(string_value = "None")]
    None,
    #[sea_orm(string_value = "Ondemand")]
    Ondemand,
    #[sea_orm(string_value = "Always")]
    Always,
}
#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, serde::Serialize, serde::Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "CheckMethod")]
pub enum CheckMethod {
    #[sea_orm(string_value = "AlarmedPixels")]
    AlarmedPixels,
    #[sea_orm(string_value = "FilteredPixels")]
    FilteredPixels,
    #[sea_orm(string_value = "Blobs")]
    Blobs,
}
#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, serde::Serialize, serde::Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "Control")]
pub enum Control {
    #[sea_orm(string_value = "None")]
    None,
    #[sea_orm(string_value = "View")]
    View,
    #[sea_orm(string_value = "Edit")]
    Edit,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    serde::Serialize,
    serde::Deserialize,
    ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "Decoding")]
pub enum Decoding {
    #[sea_orm(string_value = "None")]
    None,
    #[sea_orm(string_value = "Ondemand")]
    Ondemand,
    #[sea_orm(string_value = "KeyFrames")]
    KeyFrames,
    #[sea_orm(string_value = "KeyFrames+Ondemand")]
    #[serde(rename = "KeyFrames+Ondemand", alias = "KeyFramesOndemand")]
    KeyFramesOndemand,
    #[sea_orm(string_value = "Always")]
    Always,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    serde::Serialize,
    serde::Deserialize,
    ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "DefaultCodec")]
pub enum DefaultCodec {
    #[sea_orm(string_value = "auto")]
    #[serde(rename = "auto", alias = "Auto")]
    Auto,
    #[sea_orm(string_value = "MP4")]
    #[serde(rename = "MP4", alias = "Mp4")]
    Mp4,
    #[sea_orm(string_value = "MJPEG")]
    #[serde(rename = "MJPEG", alias = "Mjpeg")]
    Mjpeg,
}
#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, serde::Serialize, serde::Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "Devices")]
pub enum Devices {
    #[sea_orm(string_value = "None")]
    None,
    #[sea_orm(string_value = "View")]
    View,
    #[sea_orm(string_value = "Edit")]
    Edit,
}
#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, serde::Serialize, serde::Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "EmailFormat")]
pub enum EmailFormat {
    #[sea_orm(string_value = "Individual")]
    Individual,
    #[sea_orm(string_value = "Summary")]
    Summary,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    serde::Serialize,
    serde::Deserialize,
    ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "EventCloseMode")]
pub enum EventCloseMode {
    #[sea_orm(string_value = "system")]
    #[serde(rename = "system", alias = "System")]
    System,
    #[sea_orm(string_value = "time")]
    #[serde(rename = "time", alias = "Time")]
    Time,
    #[sea_orm(string_value = "duration")]
    #[serde(rename = "duration", alias = "Duration")]
    Duration,
    #[sea_orm(string_value = "idle")]
    #[serde(rename = "idle", alias = "Idle")]
    Idle,
    #[sea_orm(string_value = "alarm")]
    #[serde(rename = "alarm", alias = "Alarm")]
    Alarm,
}
#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, serde::Serialize, serde::Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "Events")]
pub enum Events {
    #[sea_orm(string_value = "None")]
    None,
    #[sea_orm(string_value = "View")]
    View,
    #[sea_orm(string_value = "Edit")]
    Edit,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    serde::Serialize,
    serde::Deserialize,
    ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "Function")]
pub enum Function {
    #[sea_orm(string_value = "None")]
    None,
    #[sea_orm(string_value = "Monitor")]
    Monitor,
    #[sea_orm(string_value = "Modect")]
    Modect,
    #[sea_orm(string_value = "Record")]
    Record,
    #[sea_orm(string_value = "Mocord")]
    Mocord,
    #[sea_orm(string_value = "Nodect")]
    Nodect,
}
#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, serde::Serialize, serde::Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "Groups")]
pub enum Groups {
    #[sea_orm(string_value = "None")]
    None,
    #[sea_orm(string_value = "View")]
    View,
    #[sea_orm(string_value = "Edit")]
    Edit,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    serde::Serialize,
    serde::Deserialize,
    ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "Importance")]
pub enum Importance {
    #[sea_orm(string_value = "Normal")]
    Normal,
    #[sea_orm(string_value = "Less")]
    Less,
    #[sea_orm(string_value = "Not")]
    Not,
}
#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, serde::Serialize, serde::Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "Monitors")]
pub enum Monitors {
    #[sea_orm(string_value = "None")]
    None,
    #[sea_orm(string_value = "View")]
    View,
    #[sea_orm(string_value = "Edit")]
    Edit,
    #[sea_orm(string_value = "Create")]
    Create,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    serde::Serialize,
    serde::Deserialize,
    ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "Orientation")]
pub enum Orientation {
    #[sea_orm(string_value = "ROTATE_0")]
    #[serde(rename = "ROTATE_0", alias = "Rotate0")]
    Rotate0,
    #[sea_orm(string_value = "ROTATE_90")]
    #[serde(rename = "ROTATE_90", alias = "Rotate90")]
    Rotate90,
    #[sea_orm(string_value = "ROTATE_180")]
    #[serde(rename = "ROTATE_180", alias = "Rotate180")]
    Rotate180,
    #[sea_orm(string_value = "ROTATE_270")]
    #[serde(rename = "ROTATE_270", alias = "Rotate270")]
    Rotate270,
    #[sea_orm(string_value = "FLIP_HORI")]
    #[serde(rename = "FLIP_HORI", alias = "FlipHori")]
    FlipHori,
    #[sea_orm(string_value = "FLIP_VERT")]
    #[serde(rename = "FLIP_VERT", alias = "FlipVert")]
    FlipVert,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    serde::Serialize,
    serde::Deserialize,
    ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "OutputContainer")]
pub enum OutputContainer {
    #[sea_orm(string_value = "auto")]
    #[serde(rename = "auto", alias = "Auto")]
    Auto,
    #[sea_orm(string_value = "mp4")]
    #[serde(rename = "mp4", alias = "Mp4")]
    Mp4,
    #[sea_orm(string_value = "mkv")]
    #[serde(rename = "mkv", alias = "Mkv")]
    Mkv,
    #[sea_orm(string_value = "webm")]
    #[serde(rename = "webm", alias = "Webm")]
    Webm,
}
#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, serde::Serialize, serde::Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "Permission")]
pub enum Permission {
    #[sea_orm(string_value = "Inherit")]
    Inherit,
    #[sea_orm(string_value = "None")]
    None,
    #[sea_orm(string_value = "View")]
    View,
    #[sea_orm(string_value = "Edit")]
    Edit,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    serde::Serialize,
    serde::Deserialize,
    ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "StreamChannel")]
pub enum StreamChannel {
    #[sea_orm(string_value = "Restream")]
    Restream,
    #[sea_orm(string_value = "CameraDirectPrimary")]
    CameraDirectPrimary,
    #[sea_orm(string_value = "CameraDirectSecondary")]
    CameraDirectSecondary,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    serde::Serialize,
    serde::Deserialize,
    ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "RTSP2WebType")]
pub enum Rtsp2WebType {
    #[sea_orm(string_value = "HLS")]
    #[serde(rename = "HLS", alias = "Hls")]
    Hls,
    #[sea_orm(string_value = "MSE")]
    #[serde(rename = "MSE", alias = "Mse")]
    Mse,
    #[sea_orm(string_value = "WebRTC")]
    #[serde(rename = "WebRTC", alias = "WebRtc")]
    WebRtc,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    serde::Serialize,
    serde::Deserialize,
    ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "Recording")]
pub enum Recording {
    #[sea_orm(string_value = "None")]
    None,
    #[sea_orm(string_value = "OnMotion")]
    OnMotion,
    #[sea_orm(string_value = "Always")]
    Always,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    serde::Serialize,
    serde::Deserialize,
    ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "RecordingSource")]
pub enum RecordingSource {
    #[sea_orm(string_value = "Primary")]
    Primary,
    #[sea_orm(string_value = "Secondary")]
    Secondary,
    #[sea_orm(string_value = "Both")]
    Both,
}
#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, serde::Serialize, serde::Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "Scheme")]
pub enum Scheme {
    #[sea_orm(string_value = "Deep")]
    Deep,
    #[sea_orm(string_value = "Medium")]
    Medium,
    #[sea_orm(string_value = "Shallow")]
    Shallow,
}
#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, serde::Serialize, serde::Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "Snapshots")]
pub enum Snapshots {
    #[sea_orm(string_value = "None")]
    None,
    #[sea_orm(string_value = "View")]
    View,
    #[sea_orm(string_value = "Edit")]
    Edit,
}
#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, serde::Serialize, serde::Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "Status")]
pub enum Status {
    #[sea_orm(string_value = "Unknown")]
    Unknown,
    #[sea_orm(string_value = "NotRunning")]
    NotRunning,
    #[sea_orm(string_value = "Running")]
    Running,
    #[sea_orm(string_value = "Connected")]
    Connected,
}
#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, serde::Serialize, serde::Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "Stream")]
pub enum Stream {
    #[sea_orm(string_value = "None")]
    None,
    #[sea_orm(string_value = "View")]
    View,
}
#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, serde::Serialize, serde::Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "System")]
pub enum System {
    #[sea_orm(string_value = "None")]
    None,
    #[sea_orm(string_value = "View")]
    View,
    #[sea_orm(string_value = "Edit")]
    Edit,
}
#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, serde::Serialize, serde::Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "ZoneType")]
pub enum ZoneType {
    #[sea_orm(string_value = "Active")]
    Active,
    #[sea_orm(string_value = "Inclusive")]
    Inclusive,
    #[sea_orm(string_value = "Exclusive")]
    Exclusive,
    #[sea_orm(string_value = "Preclusive")]
    Preclusive,
    #[sea_orm(string_value = "Inactive")]
    Inactive,
    #[sea_orm(string_value = "Privacy")]
    Privacy,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    serde::Serialize,
    serde::Deserialize,
    ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "MonitorType")]
pub enum MonitorType {
    #[sea_orm(string_value = "Local")]
    Local,
    #[sea_orm(string_value = "Remote")]
    Remote,
    #[sea_orm(string_value = "File")]
    File,
    #[sea_orm(string_value = "Ffmpeg")]
    Ffmpeg,
    #[sea_orm(string_value = "Libvlc")]
    Libvlc,
    #[sea_orm(string_value = "cURL")]
    #[serde(rename = "cURL", alias = "Curl")]
    Curl,
    #[sea_orm(string_value = "WebSite")]
    WebSite,
    #[sea_orm(string_value = "VNC")]
    #[serde(rename = "VNC", alias = "Vnc")]
    Vnc,
}

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    serde::Serialize,
    serde::Deserialize,
    ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "DeviceType")]
pub enum DeviceType {
    #[sea_orm(string_value = "X10")]
    X10,
}

#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, serde::Serialize, serde::Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "Units")]
pub enum Units {
    #[sea_orm(string_value = "Pixels")]
    Pixels,
    #[sea_orm(string_value = "Percent")]
    Percent,
}

#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, serde::Serialize, serde::Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "FrameType")]
pub enum FrameType {
    #[sea_orm(string_value = "Normal")]
    Normal,
    #[sea_orm(string_value = "Bulk")]
    Bulk,
    #[sea_orm(string_value = "Alarm")]
    Alarm,
}

#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, serde::Serialize, serde::Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "StorageType")]
pub enum StorageType {
    #[sea_orm(string_value = "local")]
    #[serde(rename = "local", alias = "Local")]
    Local,
    #[sea_orm(string_value = "s3fs")]
    #[serde(rename = "s3fs", alias = "S3fs")]
    S3fs,
}

/// Render lifecycle of a motion-synopsis row (zm-api-owned `event_synopsis`
/// table — not part of ZoneMinder's schema). Stored as a short portable string
/// column, so the migration needs no native DB `ENUM` type.
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    serde::Serialize,
    serde::Deserialize,
    ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::N(16))")]
#[serde(rename_all = "lowercase")]
pub enum SynopsisStatus {
    /// Manifest ingested; nothing rendered yet.
    #[sea_orm(string_value = "pending")]
    #[serde(rename = "pending", alias = "Pending")]
    Pending,
    /// A render task is in flight.
    #[sea_orm(string_value = "generating")]
    #[serde(rename = "generating", alias = "Generating")]
    Generating,
    /// A rendered artifact is cached and servable.
    #[sea_orm(string_value = "ready")]
    #[serde(rename = "ready", alias = "Ready")]
    Ready,
    /// The render failed (missing assets, no encoder, …); safe to retry.
    #[sea_orm(string_value = "failed")]
    #[serde(rename = "failed", alias = "Failed")]
    Failed,
}

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    serde::Serialize,
    serde::Deserialize,
    ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "WhatDisplay")]
pub enum WhatDisplay {
    #[sea_orm(string_value = "OnlyVideo")]
    OnlyVideo,
    #[sea_orm(string_value = "OnlyAudioVisualization")]
    OnlyAudioVisualization,
    #[sea_orm(string_value = "VideoAudioVisualization")]
    VideoAudioVisualization,
}

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    serde::Serialize,
    serde::Deserialize,
    ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "Framework")]
// serde renames mirror the DB spelling so a value a GET returns is a value a
// POST/PATCH accepts (the GET->POST round-trip problem fixed for monitors in
// GH #18). Without these, the API would emit "ONNX" but only accept "Onnx".
pub enum Framework {
    #[sea_orm(string_value = "TensorFlow")]
    TensorFlow,
    #[sea_orm(string_value = "PyTorch")]
    PyTorch,
    #[sea_orm(string_value = "ONNX")]
    #[serde(rename = "ONNX")]
    Onnx,
    #[sea_orm(string_value = "OpenVINO")]
    #[serde(rename = "OpenVINO")]
    OpenVino,
    #[sea_orm(string_value = "TensorRT")]
    #[serde(rename = "TensorRT")]
    TensorRt,
    #[sea_orm(string_value = "Other")]
    Other,
}

#[cfg(test)]
mod tests {
    use super::*;
    use sea_orm::ActiveEnum;

    /// Every variant must serialize to the value ZoneMinder actually stores
    /// (GH #59).
    ///
    /// `#[sea_orm(string_value = …)]` governs only the database mapping; serde
    /// defaults to the Rust variant name. Where the two spellings differ —
    /// `ROTATE_90` vs `Rotate90`, `cURL` vs `Curl` — the API was emitting a
    /// value ZoneMinder does not use, and the mismatch was invisible because
    /// requests accepted the same wrong spelling they emitted. Anything that
    /// knows the real values (the PHP UI, the CakePHP API, a client ported from
    /// either) saw a value it could not match.
    ///
    /// Written as a macro over `ActiveEnum::values()` rather than a hand-listed
    /// table so a newly generated enum is covered without anyone remembering
    /// to add it.
    macro_rules! assert_serializes_to_db_values {
        ($($ty:ty),+ $(,)?) => {$({
            for value in <$ty as ActiveEnum>::values() {
                let db: String = value.to_string();
                let parsed = <$ty as ActiveEnum>::try_from_value(&value)
                    .expect("value() round-trips through try_from_value");
                let json = serde_json::to_value(&parsed).expect("serialize");
                let wire = json.as_str().expect("enums serialize as strings");
                assert_eq!(
                    wire,
                    db,
                    "{}::{:?} serializes as {:?} but ZoneMinder stores {:?} — \
                     add #[serde(rename = {:?})]",
                    stringify!($ty), parsed, wire, db, db
                );
            }
        })+};
    }

    #[test]
    fn enums_serialize_to_the_values_zoneminder_stores() {
        assert_serializes_to_db_values!(
            Orientation,
            MonitorType,
            DefaultCodec,
            EventCloseMode,
            Rtsp2WebType,
            Decoding,
            OutputContainer,
            StorageType,
            SynopsisStatus,
            Framework,
        );
    }

    #[test]
    fn the_previous_rust_variant_spelling_is_still_accepted() {
        // Clients written against the old (incorrect) output keep working while
        // they migrate: the alias deserializes, even though it is never emitted.
        let from_old: Orientation = serde_json::from_str("\"Rotate90\"").expect("alias accepted");
        assert_eq!(from_old, Orientation::Rotate90);
        let from_new: Orientation =
            serde_json::from_str("\"ROTATE_90\"").expect("db value accepted");
        assert_eq!(from_new, Orientation::Rotate90);
        assert_eq!(
            serde_json::to_value(Orientation::Rotate90).unwrap(),
            serde_json::json!("ROTATE_90"),
            "the DB spelling is what goes on the wire"
        );

        let curl: MonitorType = serde_json::from_str("\"Curl\"").expect("alias accepted");
        assert_eq!(curl, MonitorType::Curl);
        assert_eq!(
            serde_json::to_value(MonitorType::Curl).unwrap(),
            serde_json::json!("cURL")
        );
    }
}
