//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use super::sea_orm_active_enums::Status;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Servers")]
pub struct Model {
    #[sea_orm(column_name = "Id", primary_key)]
    pub id: u32,
    #[sea_orm(column_name = "Protocol", column_type = "Text", nullable)]
    pub protocol: Option<String>,
    #[sea_orm(column_name = "Hostname", column_type = "Text", nullable)]
    pub hostname: Option<String>,
    #[sea_orm(column_name = "Port")]
    pub port: Option<u32>,
    #[sea_orm(column_name = "PathToIndex", column_type = "Text", nullable)]
    pub path_to_index: Option<String>,
    #[sea_orm(column_name = "PathToZMS", column_type = "Text", nullable)]
    pub path_to_zms: Option<String>,
    #[sea_orm(column_name = "PathToApi", column_type = "Text", nullable)]
    pub path_to_api: Option<String>,
    #[sea_orm(column_name = "Name")]
    pub name: String,
    #[sea_orm(column_name = "State_Id")]
    pub state_id: Option<u32>,
    #[sea_orm(column_name = "Status")]
    pub status: Status,
    #[sea_orm(
        column_name = "CpuLoad",
        column_type = "Decimal(Some((5, 1)))",
        nullable
    )]
    pub cpu_load: Option<Decimal>,
    #[sea_orm(
        column_name = "CpuUserPercent",
        column_type = "Decimal(Some((5, 1)))",
        nullable
    )]
    pub cpu_user_percent: Option<Decimal>,
    #[sea_orm(
        column_name = "CpuNicePercent",
        column_type = "Decimal(Some((5, 1)))",
        nullable
    )]
    pub cpu_nice_percent: Option<Decimal>,
    #[sea_orm(
        column_name = "CpuSystemPercent",
        column_type = "Decimal(Some((5, 1)))",
        nullable
    )]
    pub cpu_system_percent: Option<Decimal>,
    #[sea_orm(
        column_name = "CpuIdlePercent",
        column_type = "Decimal(Some((5, 1)))",
        nullable
    )]
    pub cpu_idle_percent: Option<Decimal>,
    #[sea_orm(
        column_name = "CpuUsagePercent",
        column_type = "Decimal(Some((5, 1)))",
        nullable
    )]
    pub cpu_usage_percent: Option<Decimal>,
    #[sea_orm(column_name = "TotalMem")]
    pub total_mem: Option<u64>,
    #[sea_orm(column_name = "FreeMem")]
    pub free_mem: Option<u64>,
    #[sea_orm(column_name = "TotalSwap")]
    pub total_swap: Option<u64>,
    #[sea_orm(column_name = "FreeSwap")]
    pub free_swap: Option<u64>,
    pub zmstats: i8,
    pub zmaudit: i8,
    pub zmtrigger: i8,
    pub zmeventnotification: i8,
    #[sea_orm(
        column_name = "Latitude",
        column_type = "Decimal(Some((10, 8)))",
        nullable
    )]
    pub latitude: Option<Decimal>,
    #[sea_orm(
        column_name = "Longitude",
        column_type = "Decimal(Some((11, 8)))",
        nullable
    )]
    pub longitude: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
