//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Server_Stats")]
pub struct Model {
    #[sea_orm(column_name = "Id", primary_key)]
    pub id: u32,
    #[sea_orm(column_name = "ServerId")]
    pub server_id: Option<u32>,
    #[sea_orm(column_name = "TimeStamp")]
    pub time_stamp: DateTimeUtc,
    #[sea_orm(
        column_name = "CpuLoad",
        column_type = "Decimal(Some((5, 1)))",
        nullable
    )]
    pub cpu_load: Option<Decimal>,
    #[sea_orm(
        column_name = "CpuUserPercent",
        column_type = "Decimal(Some((5, 1)))",
        nullable
    )]
    pub cpu_user_percent: Option<Decimal>,
    #[sea_orm(
        column_name = "CpuNicePercent",
        column_type = "Decimal(Some((5, 1)))",
        nullable
    )]
    pub cpu_nice_percent: Option<Decimal>,
    #[sea_orm(
        column_name = "CpuSystemPercent",
        column_type = "Decimal(Some((5, 1)))",
        nullable
    )]
    pub cpu_system_percent: Option<Decimal>,
    #[sea_orm(
        column_name = "CpuIdlePercent",
        column_type = "Decimal(Some((5, 1)))",
        nullable
    )]
    pub cpu_idle_percent: Option<Decimal>,
    #[sea_orm(
        column_name = "CpuUsagePercent",
        column_type = "Decimal(Some((5, 1)))",
        nullable
    )]
    pub cpu_usage_percent: Option<Decimal>,
    #[sea_orm(column_name = "TotalMem")]
    pub total_mem: Option<u64>,
    #[sea_orm(column_name = "FreeMem")]
    pub free_mem: Option<u64>,
    #[sea_orm(column_name = "TotalSwap")]
    pub total_swap: Option<u64>,
    #[sea_orm(column_name = "FreeSwap")]
    pub free_swap: Option<u64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
