//! The MySQL trigger set from db/triggers.sql as of the vendored
//! upstream snapshot. Generated by scripts/gen_baseline_migration.py
//! --emit-mysql-triggers - edit the generator, not this file.

/// (trigger name, CREATE TRIGGER statement).
pub(crate) fn mysql_triggers() -> Vec<(&'static str, &'static str)> {
    vec![
        (
            "event_update_trigger",
            r#"CREATE TRIGGER event_update_trigger AFTER UPDATE ON Events
FOR EACH ROW
BEGIN
  DECLARE diff BIGINT DEFAULT 0;
  DECLARE hour_rows  INT DEFAULT 0;
  DECLARE day_rows   INT DEFAULT 0;
  DECLARE week_rows  INT DEFAULT 0;
  DECLARE month_rows INT DEFAULT 0;

  SET diff = COALESCE(NEW.DiskSpace, 0) - COALESCE(OLD.DiskSpace, 0);

  IF diff != 0 THEN
    UPDATE Events_Hour  SET DiskSpace = NEW.DiskSpace WHERE EventId = NEW.Id;
    SET hour_rows = ROW_COUNT();
    UPDATE Events_Day   SET DiskSpace = NEW.DiskSpace WHERE EventId = NEW.Id;
    SET day_rows = ROW_COUNT();
    UPDATE Events_Week  SET DiskSpace = NEW.DiskSpace WHERE EventId = NEW.Id;
    SET week_rows = ROW_COUNT();
    UPDATE Events_Month SET DiskSpace = NEW.DiskSpace WHERE EventId = NEW.Id;
    SET month_rows = ROW_COUNT();

    UPDATE Event_Summaries SET
      HourEventDiskSpace  = GREATEST(COALESCE(HourEventDiskSpace, 0)  + hour_rows  * diff, 0),
      DayEventDiskSpace   = GREATEST(COALESCE(DayEventDiskSpace, 0)   + day_rows   * diff, 0),
      WeekEventDiskSpace  = GREATEST(COALESCE(WeekEventDiskSpace, 0)  + week_rows  * diff, 0),
      MonthEventDiskSpace = GREATEST(COALESCE(MonthEventDiskSpace, 0) + month_rows * diff, 0),
      TotalEventDiskSpace = GREATEST(COALESCE(TotalEventDiskSpace, 0) + diff, 0)
    WHERE MonitorId = OLD.MonitorId;
  END IF;

  IF NEW.Archived != OLD.Archived THEN
    IF NEW.Archived THEN
      INSERT INTO Events_Archived (EventId, MonitorId, DiskSpace)
        VALUES (NEW.Id, NEW.MonitorId, NEW.DiskSpace);
      INSERT INTO Event_Summaries (MonitorId, ArchivedEvents, ArchivedEventDiskSpace)
        VALUES (NEW.MonitorId, 1, NEW.DiskSpace)
        ON DUPLICATE KEY UPDATE
          ArchivedEvents = COALESCE(ArchivedEvents, 0) + 1,
          ArchivedEventDiskSpace = COALESCE(ArchivedEventDiskSpace, 0) + COALESCE(NEW.DiskSpace, 0);
    ELSEIF OLD.Archived THEN
      DELETE FROM Events_Archived WHERE EventId = OLD.Id;
      UPDATE Event_Summaries SET
        ArchivedEvents = GREATEST(COALESCE(ArchivedEvents, 0) - 1, 0),
        ArchivedEventDiskSpace = GREATEST(COALESCE(ArchivedEventDiskSpace, 0) - COALESCE(OLD.DiskSpace, 0), 0)
      WHERE MonitorId = OLD.MonitorId;
    END IF;
  ELSEIF NEW.Archived AND diff != 0 THEN
    UPDATE Events_Archived SET DiskSpace = NEW.DiskSpace WHERE EventId = NEW.Id;
    UPDATE Event_Summaries SET
      ArchivedEventDiskSpace = GREATEST(COALESCE(ArchivedEventDiskSpace, 0) + diff, 0)
    WHERE MonitorId = OLD.MonitorId;
  END IF;
END
"#,
        ),
        (
            "event_delete_trigger",
            r#"CREATE TRIGGER event_delete_trigger BEFORE DELETE ON Events
FOR EACH ROW
BEGIN
  DECLARE hour_rows  INT DEFAULT 0;
  DECLARE day_rows   INT DEFAULT 0;
  DECLARE week_rows  INT DEFAULT 0;
  DECLARE month_rows INT DEFAULT 0;

  DELETE FROM Events_Hour  WHERE EventId = OLD.Id;  SET hour_rows  = ROW_COUNT();
  DELETE FROM Events_Day   WHERE EventId = OLD.Id;  SET day_rows   = ROW_COUNT();
  DELETE FROM Events_Week  WHERE EventId = OLD.Id;  SET week_rows  = ROW_COUNT();
  DELETE FROM Events_Month WHERE EventId = OLD.Id;  SET month_rows = ROW_COUNT();

  IF OLD.Archived THEN
    DELETE FROM Events_Archived WHERE EventId = OLD.Id;
    UPDATE Event_Summaries SET
      HourEvents             = GREATEST(COALESCE(HourEvents, 0)             - hour_rows, 0),
      HourEventDiskSpace     = GREATEST(COALESCE(HourEventDiskSpace, 0)     - hour_rows  * COALESCE(OLD.DiskSpace, 0), 0),
      DayEvents              = GREATEST(COALESCE(DayEvents, 0)              - day_rows, 0),
      DayEventDiskSpace      = GREATEST(COALESCE(DayEventDiskSpace, 0)      - day_rows   * COALESCE(OLD.DiskSpace, 0), 0),
      WeekEvents             = GREATEST(COALESCE(WeekEvents, 0)             - week_rows, 0),
      WeekEventDiskSpace     = GREATEST(COALESCE(WeekEventDiskSpace, 0)     - week_rows  * COALESCE(OLD.DiskSpace, 0), 0),
      MonthEvents            = GREATEST(COALESCE(MonthEvents, 0)            - month_rows, 0),
      MonthEventDiskSpace    = GREATEST(COALESCE(MonthEventDiskSpace, 0)    - month_rows * COALESCE(OLD.DiskSpace, 0), 0),
      TotalEvents            = GREATEST(COALESCE(TotalEvents, 0) - 1, 0),
      TotalEventDiskSpace    = GREATEST(COALESCE(TotalEventDiskSpace, 0)    - COALESCE(OLD.DiskSpace, 0), 0),
      ArchivedEvents         = GREATEST(COALESCE(ArchivedEvents, 0) - 1, 0),
      ArchivedEventDiskSpace = GREATEST(COALESCE(ArchivedEventDiskSpace, 0) - COALESCE(OLD.DiskSpace, 0), 0)
    WHERE MonitorId = OLD.MonitorId;
  ELSE
    UPDATE Event_Summaries SET
      HourEvents          = GREATEST(COALESCE(HourEvents, 0)          - hour_rows, 0),
      HourEventDiskSpace  = GREATEST(COALESCE(HourEventDiskSpace, 0)  - hour_rows  * COALESCE(OLD.DiskSpace, 0), 0),
      DayEvents           = GREATEST(COALESCE(DayEvents, 0)           - day_rows, 0),
      DayEventDiskSpace   = GREATEST(COALESCE(DayEventDiskSpace, 0)   - day_rows   * COALESCE(OLD.DiskSpace, 0), 0),
      WeekEvents          = GREATEST(COALESCE(WeekEvents, 0)          - week_rows, 0),
      WeekEventDiskSpace  = GREATEST(COALESCE(WeekEventDiskSpace, 0)  - week_rows  * COALESCE(OLD.DiskSpace, 0), 0),
      MonthEvents         = GREATEST(COALESCE(MonthEvents, 0)         - month_rows, 0),
      MonthEventDiskSpace = GREATEST(COALESCE(MonthEventDiskSpace, 0) - month_rows * COALESCE(OLD.DiskSpace, 0), 0),
      TotalEvents         = GREATEST(COALESCE(TotalEvents, 0) - 1, 0),
      TotalEventDiskSpace = GREATEST(COALESCE(TotalEventDiskSpace, 0) - COALESCE(OLD.DiskSpace, 0), 0)
    WHERE MonitorId = OLD.MonitorId;
  END IF;
END
"#,
        ),
        (
            "Zone_Insert_Trigger",
            r#"CREATE TRIGGER Zone_Insert_Trigger AFTER INSERT ON Zones
FOR EACH ROW
  BEGIN
    UPDATE Monitors SET ZoneCount=(SELECT COUNT(*) FROM Zones WHERE MonitorId=NEW.MonitorId) WHERE Monitors.Id=NEW.MonitorID;
  END
"#,
        ),
        (
            "Zone_Delete_Trigger",
            r#"CREATE TRIGGER Zone_Delete_Trigger AFTER DELETE ON Zones
FOR EACH ROW
  BEGIN
    UPDATE Monitors SET ZoneCount=(SELECT COUNT(*) FROM Zones WHERE MonitorId=OLD.MonitorId) WHERE Monitors.Id=OLD.MonitorID;
  END
"#,
        ),
    ]
}
