#!/usr/bin/env python3
"""Generate src/migration/legacy_bridge/chain.rs from the frozen legacy
update chain vendored under db/legacy/.

    python3 scripts/gen_legacy_chain.py --zm-version 1.39.17

The chain is frozen forever and pruned to the 1.34.0 support floor: it is
only refreshed (together with the --zm-version cutover marker) when the
vendored ZoneMinder schema snapshot is refreshed before the cutover release.
"""

import argparse
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LEGACY_DIR = ROOT / "db" / "legacy"
OUT = ROOT / "src" / "migration" / "legacy_bridge" / "chain.rs"


def vkey(v: str):
    return tuple(int(x) for x in v.split("."))


def inline_sources():
    """Inline `source @PKGDATADIR@/db/X.sql` client directives using the
    current vendored fragments in db/ - matching zmupdate.pl semantics,
    where `source` resolves against the target release's installed files.
    Idempotent: inlined files contain no source lines."""
    import re as _re
    for f in LEGACY_DIR.glob("zm_update-*.sql"):
        text = f.read_text()
        if "source @PKGDATADIR@" not in text:
            continue
        def repl(m):
            frag = ROOT / "db" / f"{m.group(1)}.sql"
            assert frag.exists(), f"missing fragment {frag} for {f.name}"
            return frag.read_text()
        new_text = _re.sub(r"(?m)^source\s+@PKGDATADIR@/db/(\w+)\.sql\s*$", repl, text)
        f.write_text(new_text)
        print(f"inlined source directives in {f.name}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--zm-version", required=True,
                    help="ZM_VERSION of the vendored snapshot (the cutover version)")
    args = ap.parse_args()

    inline_sources()
    files = sorted(LEGACY_DIR.glob("zm_update-*.sql"),
                   key=lambda f: vkey(re.match(r"zm_update-([\d.]+)\.sql", f.name).group(1)))
    assert files, f"no chain files in {LEGACY_DIR}"

    lines = [
        "//! The frozen legacy zm_update-*.sql chain, embedded verbatim from",
        "//! db/legacy/ (cmake @vars@ substituted at vendor time). Generated by",
        "//! scripts/gen_legacy_chain.py - edit the generator, not this file.",
        "",
        "/// ZM_VERSION of the vendored schema snapshot: the version whose",
        "/// schema equals the baseline migration. The bridge records this in",
        "/// ZM_DYN_DB_VERSION / ZM_DYN_CURR_VERSION after stamping.",
        f'pub(crate) const CUTOVER_ZM_VERSION: &str = "{args.zm_version}";',
        "",
        "/// (version, sql) in ascending version order.",
        "pub(super) const CHAIN: &[(&str, &str)] = &[",
    ]
    for f in files:
        v = re.match(r"zm_update-([\d.]+)\.sql", f.name).group(1)
        lines.append(f'    ("{v}", include_str!("../../../db/legacy/{f.name}")),')
    lines.append("];")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    subprocess.run(["rustfmt", "--edition", "2021", str(OUT)], check=True)
    print(f"wrote {OUT} ({len(files)} chain files, cutover {args.zm_version})")


if __name__ == "__main__":
    main()
